# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33913442ef513ab112b271b64c55a9ca9225c750783b1672446bf65ea501d441c1f1054ed01f77f787e2c71edb4b832970fc988c97ad31704e6af9f0c70fe60d

test:
  secret_key_base: 588e2cc59ce7dda40cc7c3cdfd34f69def783c5bacf5bf62e4a0aa2f30e823d329d71c18f4182a05e2569abfc462827064e83fce54df550e652f8bde3832aae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
